### ISSUE TITLE
[PE-D][Tester A] Unclear error message for tag names 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-2/tp#221]
First i keyed in:  student n/John Doe id/A0123456X p/98765432 e/johnd@example.com a/311, Clementi Ave 2,  t/2, #02-25 t/friends t/owesMoney

The t/2 within the address parameter was meant to be an 'uninteded' typo by the user or a slim chance it is part of the address name. 

Hence, I do not think the error message presented is the most appropraite as the user, I checked that my t/friends and t/owesMoney met the criteria. 

![Screenshot 2024-11-08 at 4.50.12 PM (2).png](https://raw.githubusercontent.com/jeremychiaaaaa/ped/main/files/b397bef5-f30f-4c56-b03e-723f13987cb9.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jeremychiaaaaa/ped#4

**Comment by charlenetcy** [comment]
As tags are required to be non empty and only alphanumeric with no spaces, we could include that under the specifications of the tag in the company and student sections. 

Not sure about handling the t/ being in the address input though, as it would be considered as a tag, and fails due to the comma. Even if the comma is excluded, the space between the t/2 and the rest of the address would make AdmiNUS think a tag t/2 REST_OF_ADDRESS is being added which would similarly trigger the same error message.

**Comment by ruiming97** [comment]
I think can ignore the `t/` handling in address inputs since rarely have addresses with `t/`
