### ISSUE TITLE
[PE-D][Tester B] View Stuck on First Contact with Same Name After Creating Multiple Contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-2/tp#229]
When multiple contacts are created with the same name and tags but different information, clicking on any of these contacts does not change the view properly. Instead, the view gets stuck displaying the details of the first contact with that specific name, regardless of which contact is clicked. This issue prevents users from accessing and viewing the details of other contacts with the same name.

Here's how to recreate the bug:
1)Add 2 contacts with the same name but different information
2)Click on one of the contacts
3)Click on the other contact

The contact shown will be stuck on the first contact with that name

![image.png](https://raw.githubusercontent.com/junyi73/ped/main/files/e35c0252-69da-4004-8813-ad3740989dfd.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: junyi73/ped#3

**Comment by JiaYi-Gallium369** [comment]
We tested and tried on contacts with same name, but different information. The contact details changes accordingly.

In the UG, it is already stated that there is a `view` command to view a specific contact in the list. So, as this is a CLI-based app, it is more preferred to use the `view` command instead of clicking on the contacts in the list.

But still, we tried both the `view` and click method to test. The contact information changes accordingly and does not stuck on the first contact with that specific name.
